# Generated by Django 2.1 on 2019-04-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JOB_LOG',
            fields=[
                ('JOB_LOG_PK', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IS_COMPLETE', models.CharField(max_length=50, null=True)),
                ('SUBMIT_DT', models.DateTimeField(null=True)),
                ('XPR_JOB_ID', models.CharField(max_length=50, null=True)),
                ('OVRD_FILE_PATH', models.CharField(max_length=500, null=True)),
                ('JOB_STATUS', models.CharField(max_length=50, null=True)),
                ('API_JOB_NAME', models.CharField(max_length=50, null=True)),
                ('X_RUN_ID', models.CharField(max_length=100, null=True)),
                ('X_PROCESS_ID', models.CharField(max_length=50, null=True)),
                ('X_LOG_PATH', models.CharField(max_length=200, null=True)),
                ('X_SERVER', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
